[program:salesly-api]
directory=/app/
process_name=%(program_name)s
command=gunicorn config.asgi:application
autostart=true
startretries=2
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=4
stdout_logfile=/var/log/supervisor/%(program_name)s.log
user=root
